import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@mantine/core/styles.css';

import { MantineProvider, ColorSchemeScript } from '@mantine/core';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider



          theme={{
            primaryColor: 'pink',
            colors: {
              'pink': [
                "#ffebf4",
                "#fbd7e4",
                "#edaec3",
                "#e182a2",
                "#d75d86",
                "#d14675",
                "#cf396c",
                "#b82a5b",
                "#a62251",
                "#921545"
              ],
            },
          }}>{children}</MantineProvider>
      </body>
    </html>
  )
}
