version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
      - "4000:4000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: doodle
    working_dir: /app
    command: sh -c "npm install && node app.js"
    restart: always

  db:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: doodle
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

volumes:
  db_data:
