const WORDS = [
    "Apple", "Tree", "Bicycle", "Moon", "Pizza", "Sunflower", "Elephant", "Guitar", "Clock", "House",
    "Car", "Penguin", "Soccer ball", "Butterfly", "Mountain", "Robot", "Fish", "Rainbow", "Ice cream", "Book",
    "Snail", "Train", "Dolphin", "Camera", "Cake", "UFO", "Dragon", "Astronaut", "Unicorn", "Jungle",
    "Pirate", "Telescope", "Cactus", "Mouse", "Helicopter", "Snowman", "Palm tree", "Cow", "Bridge", "Ghost",
    "Bat", "Kangaroo", "Sailboat", "Pineapple", "Bathtub", "Teapot", "Dragonfly", "Eiffel Tower", "Pencil", "Hot air balloon",
    "Snowflake", "Whale", "Zebra", "Lemon", "Hamburger", "Toothbrush", "Spider", "Castle", "Rocket", "Jellyfish",
    "Star", "Hat", "Dog", "Anchor", "Strawberry", "Cupcake", "Owl", "TV", "Key", "Chessboard", "Lipstick",
    "Microphone", "Sandcastle", "Pinecone", "Squirrel", "Ice cream cone", "Fireworks", "Peacock", "Crayon", "Panda", "Easel",
    "Saxophone", "Caterpillar", "Lighthouse", "Ambulance", "Seashell", "Pinecone", "Toadstool", "Chainsaw", "Pajamas", "Unicorn",
    "Fire hydrant", "Shamrock", "Thermometer", "Koala", "T-Rex", "Popsicle", "Earmuffs", "Cornucopia", "Seagull", "Firefly",
    "Sushi", "Fireplace", "Chestnut", "Easel", "Saxophone", "Skunk", "Sock", "Pretzel", "Dragon", "Elephant", "Cupcake",
    "Penguin", "Castle", "Panda", "Teapot", "Snowboard", "Hat", "Snow globe", "Pretzel", "Dragonfly", "Eiffel Tower",
    "Pencil", "Seashell", "Cactus", "Mitten", "Microphone", "Sandcastle", "Toadstool", "Chainsaw", "Dragon", "Pajamas",
    "Unicorn", "Pretzel", "Popsicle", "Earmuffs", "Cupcake", "Chestnut", "Easel", "Saxophone", "Sock", "Toadstool",
    "Pineapple", "Bathtub", "Teapot", "Toaster", "Waffle", "Firetruck", "Surfboard", "Avocado", "Pyramid", "Telescope",
    "Saxophone", "Caterpillar", "Lighthouse", "Ambulance", "Seashell", "Pinecone", "Squirrel", "Microphone", "Sandcastle", "Toadstool",
    "Chainsaw", "Dragon", "Pajamas", "Unicorn", "Fire hydrant", "Shamrock", "Thermometer", "Koala", "T-Rex", "Popsicle",
    "Earmuffs", "Cornucopia", "Seagull", "Firefly", "Sushi", "Fireplace", "Chestnut", "Easel", "Saxophone", "Skunk",
    "Sock", "Pretzel", "Dragon", "Elephant", "Cupcake", "Penguin", "Castle", "Panda", "Teapot", "Snowboard",
    "Hat", "Snow globe", "Pretzel", "Dragonfly", "Eiffel Tower", "Pencil", "Seashell", "Cactus", "Mitten", "Ice cream cone",
    "Firefly", "Cookie jar", "Mosquito", "Bulldozer", "Zebra", "Caterpillar", "Compass", "Cappuccino", "Castle", "Garbage can",
    "Seagull", "Helicopter", "Cello", "Snow globe", "Bathtub", "Toaster", "Crayon", "Seashell", "Saxophone", "Chainsaw",
    "Eiffel Tower", "Giraffe", "Dragon", "Rainbow", "Pineapple", "Cupcake", "Pretzel", "Ambulance", "Beach ball", "Toaster",
    "Saxophone", "Penguin", "Sphinx", "Ice cream truck", "Lemonade", "French fries", "Chessboard", "Jack-o'-lantern", "Disco ball",
    "Panda", "Eiffel Tower", "Pineapple", "Submarine", "Raccoon", "Pajamas", "Tornado", "Pencil sharpener", "Stapler", "Seashell",
    "Cactus", "Pufferfish", "Giraffe", "Mitten", "Ice cream cone", "Firefly", "Cookie jar", "Mosquito", "Bulldozer", "Zebra",
    "Caterpillar", "Compass", "Cappuccino", "Castle", "Garbage can", "Seagull", "Helicopter", "Cello", "Snow globe", "Bathtub",
    "Toaster", "Crayon", "Seashell", "Saxophone", "Chainsaw", "Eiffel Tower", "Giraffe", "Dragon", "Rainbow", "Pineapple",
    "Cupcake", "Pretzel", "Ambulance", "Beach ball", "Chainsaw", "Panda", "Giraffe", "Saxophone", "Pinecone", "Snow globe",
    "Telescope", "Pretzel", "Toaster", "Seashell", "Giraffe", "Panda", "Saxophone", "Ambulance", "Pineapple", "Fire hydrant",
    "Chainsaw", "Pretzel", "Unicorn", "Giraffe", "Toaster", "Saxophone", "Chainsaw", "Ambulance", "Fire hydrant", "Panda",
    "Giraffe", "Saxophone", "Pinecone", "Snow globe", "Telescope", "Pretzel", "Toaster", "Seashell", "Saxophone", "Panda",
    "Giraffe", "Ambulance", "Pineapple", "Fire hydrant", "Chainsaw", "Pretzel", "Unicorn"
];

module.exports = WORDS;